#!/usr/bin/env python3
"""Database initialization script.

Creates all tables and seeds with realistic sample data for the
UK Operations BD Platform.

Usage:
    python scripts/init_db.py
"""

import os
import sys
from datetime import date, datetime, timedelta

# Allow running from project root
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from app.models.base import Base
from app.models.council import Council
from app.models.company import Company
from app.models.planning_application import PlanningApplication
from app.models.scheme import Scheme
from app.models.pipeline import PipelineOpportunity
from app.models.alert import Alert
from app.models.scraper_run import ScraperRun

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:postgres@localhost:5432/uk_ops_bd",
)


def create_tables(engine):
    """Create all tables."""
    print("Creating all tables...")
    Base.metadata.create_all(engine)
    print("  Done.")


def seed_councils(session: Session) -> list[Council]:
    """Seed 50 UK councils with realistic data."""
    print("Seeding councils...")
    councils_data = [
        # London Boroughs
        {"name": "London Borough of Tower Hamlets", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://development.towerhamlets.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Hackney", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.hackney.gov.uk/planning/search-applications", "affordable_housing_pct": 50.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Southwark", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.southwark.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Lambeth", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.lambeth.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Newham", "region": "London", "council_type": "London Borough", "portal_type": "NEC", "portal_url": "https://pa.newham.gov.uk/online-applications/", "affordable_housing_pct": 50.0, "article4_directions": False, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Greenwich", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.royalgreenwich.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Wandsworth", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.wandsworth.gov.uk/online-applications/", "affordable_housing_pct": 33.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Barking and Dagenham", "region": "London", "council_type": "London Borough", "portal_type": "NEC", "portal_url": "https://pa.lbbd.gov.uk/online-applications/", "affordable_housing_pct": 50.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Emerging"},
        {"name": "London Borough of Ealing", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://pam.ealing.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Lewisham", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.lewisham.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "City of Westminster", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://idoxpa.westminster.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Camden", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planningrecords.camden.gov.uk/Northgate/PlanningExplorer/", "affordable_housing_pct": 50.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Islington", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://planning.islington.gov.uk/online-applications/", "affordable_housing_pct": 50.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Royal Borough of Kensington and Chelsea", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://www.rbkc.gov.uk/planning/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "London Borough of Hammersmith and Fulham", "region": "London", "council_type": "London Borough", "portal_type": "Idox", "portal_url": "https://public-access.lbhf.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        # Greater Manchester
        {"name": "Manchester City Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://pa.manchester.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Salford City Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://pa.salford.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": False, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Trafford Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://publicaccess.trafford.gov.uk/online-applications/", "affordable_housing_pct": 25.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Emerging"},
        {"name": "Stockport Metropolitan Borough Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planning.stockport.gov.uk/PlanningData-online/", "affordable_housing_pct": 30.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Emerging"},
        # West Midlands
        {"name": "Birmingham City Council", "region": "West Midlands", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://eplanning.birmingham.gov.uk/Northgate/PlanningExplorer/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Coventry City Council", "region": "West Midlands", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planning.coventry.gov.uk/online-applications/", "affordable_housing_pct": 25.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Wolverhampton City Council", "region": "West Midlands", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planning.wolverhampton.gov.uk/online-applications/", "affordable_housing_pct": 25.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Adopted"},
        # Yorkshire
        {"name": "Leeds City Council", "region": "Yorkshire and the Humber", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://publicaccess.leeds.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Sheffield City Council", "region": "Yorkshire and the Humber", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planningapps.sheffield.gov.uk/online-applications/", "affordable_housing_pct": 10.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Emerging"},
        {"name": "City of Bradford Metropolitan District Council", "region": "Yorkshire and the Humber", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planning.bradford.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "City of York Council", "region": "Yorkshire and the Humber", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planningaccess.york.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Emerging"},
        # North East
        {"name": "Newcastle City Council", "region": "North East", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://publicaccess.newcastle.gov.uk/online-applications/", "affordable_housing_pct": 15.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Sunderland City Council", "region": "North East", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://planningapplications.sunderland.gov.uk/online-applications/", "affordable_housing_pct": 10.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Gateshead Council", "region": "North East", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://public.gateshead.gov.uk/online-applications/", "affordable_housing_pct": 15.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Adopted"},
        # East Midlands
        {"name": "Nottingham City Council", "region": "East Midlands", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://publicaccess.nottinghamcity.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Leicester City Council", "region": "East Midlands", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planning.leicester.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Derby City Council", "region": "East Midlands", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://eplanning.derby.gov.uk/online-applications/", "affordable_housing_pct": 30.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Adopted"},
        # South East
        {"name": "Brighton and Hove City Council", "region": "South East", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planningapps.brighton-hove.gov.uk/online-applications/", "affordable_housing_pct": 40.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Reading Borough Council", "region": "South East", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planning.reading.gov.uk/fastweb/", "affordable_housing_pct": 30.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Oxford City Council", "region": "South East", "council_type": "District Council", "portal_type": "Idox", "portal_url": "https://public.oxford.gov.uk/online-applications/", "affordable_housing_pct": 50.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Milton Keynes City Council", "region": "South East", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://publicaccess2.milton-keynes.gov.uk/online-applications/", "affordable_housing_pct": 31.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Slough Borough Council", "region": "South East", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://publicaccess.slough.gov.uk/online-applications/", "affordable_housing_pct": 30.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Emerging"},
        # South West
        {"name": "Bristol City Council", "region": "South West", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://pa.bristol.gov.uk/online-applications/", "affordable_housing_pct": 30.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Bath and North East Somerset Council", "region": "South West", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://www.bathnes.gov.uk/planning-and-building-control/", "affordable_housing_pct": 30.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Plymouth City Council", "region": "South West", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planning.plymouth.gov.uk/online-applications/", "affordable_housing_pct": 30.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Exeter City Council", "region": "South West", "council_type": "District Council", "portal_type": "Idox", "portal_url": "https://publicaccess.exeter.gov.uk/online-applications/", "affordable_housing_pct": 35.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        # East of England
        {"name": "Cambridge City Council", "region": "East of England", "council_type": "District Council", "portal_type": "Idox", "portal_url": "https://applications.greatercambridgeplanning.org/online-applications/", "affordable_housing_pct": 40.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Norwich City Council", "region": "East of England", "council_type": "District Council", "portal_type": "Idox", "portal_url": "https://planning.norwich.gov.uk/online-applications/", "affordable_housing_pct": 33.0, "article4_directions": True, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Ipswich Borough Council", "region": "East of England", "council_type": "District Council", "portal_type": "Idox", "portal_url": "https://publicaccess.ipswich.gov.uk/online-applications/", "affordable_housing_pct": 15.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Luton Borough Council", "region": "East of England", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://planning.luton.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": False, "local_plan_status": "Adopted"},
        # North West (additional)
        {"name": "Liverpool City Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://pa.liverpool.gov.uk/online-applications/", "affordable_housing_pct": 20.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Sefton Metropolitan Borough Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://pa.sefton.gov.uk/online-applications/", "affordable_housing_pct": 30.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        {"name": "Wirral Metropolitan Borough Council", "region": "North West", "council_type": "Metropolitan Borough", "portal_type": "Idox", "portal_url": "https://pa.wirral.gov.uk/online-applications/", "affordable_housing_pct": 25.0, "article4_directions": False, "btr_policy_exists": False, "cil_charging": True, "local_plan_status": "Adopted"},
        # Scotland
        {"name": "City of Edinburgh Council", "region": "Scotland", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/", "affordable_housing_pct": 25.0, "article4_directions": True, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
        {"name": "Glasgow City Council", "region": "Scotland", "council_type": "Unitary Authority", "portal_type": "Idox", "portal_url": "https://publicaccess.glasgow.gov.uk/online-applications/", "affordable_housing_pct": 25.0, "article4_directions": False, "btr_policy_exists": True, "cil_charging": False, "local_plan_status": "Adopted"},
    ]

    councils = []
    for data in councils_data:
        council = Council(**data)
        session.add(council)
        councils.append(council)

    session.flush()
    print(f"  Seeded {len(councils)} councils.")
    return councils


def seed_companies(session: Session) -> list[Company]:
    """Seed companies in the BTR/PBSA space."""
    print("Seeding companies...")
    companies_data = [
        {
            "name": "Greystar",
            "companies_house_number": "09834211",
            "sector": "BTR",
            "sub_sector": "Operator",
            "company_type": "Private",
            "website": "https://www.greystar.com/uk",
            "headquarters_address": "10 Portman Square, Marylebone",
            "headquarters_postcode": "W1H 6AZ",
            "employee_count": 850,
            "revenue_gbp": 450000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": True,
            "relationship_status": "Prospecting",
            "key_contact_name": "Mark Sherwood",
            "key_contact_title": "Managing Director, UK",
        },
        {
            "name": "Unite Students",
            "companies_house_number": "03199160",
            "sector": "PBSA",
            "sub_sector": "Developer/Operator",
            "company_type": "Public",
            "website": "https://www.unitestudents.com",
            "headquarters_address": "South Quay House, Temple Back",
            "headquarters_postcode": "BS1 6FL",
            "employee_count": 3200,
            "revenue_gbp": 620000000,
            "is_client": True,
            "is_competitor": False,
            "is_target": False,
            "relationship_status": "Active Client",
            "key_contact_name": "Richard Smith",
            "key_contact_title": "Chief Executive Officer",
        },
        {
            "name": "Legal & General",
            "companies_house_number": "01417162",
            "sector": "BTR",
            "sub_sector": "Investor/Developer",
            "company_type": "Public",
            "website": "https://www.legalandgeneral.com",
            "headquarters_address": "One Coleman Street",
            "headquarters_postcode": "EC2R 5AA",
            "employee_count": 10000,
            "revenue_gbp": 1200000000,
            "is_client": True,
            "is_competitor": False,
            "is_target": False,
            "relationship_status": "Active Client",
            "key_contact_name": "Dan Sheridan",
            "key_contact_title": "Head of BTR",
        },
        {
            "name": "Grainger PLC",
            "companies_house_number": "00125575",
            "sector": "BTR",
            "sub_sector": "Developer/Operator",
            "company_type": "Public",
            "website": "https://www.graingerplc.co.uk",
            "headquarters_address": "Citygate, St James' Boulevard",
            "headquarters_postcode": "NE1 4JE",
            "employee_count": 600,
            "revenue_gbp": 380000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": True,
            "relationship_status": "Warm Lead",
            "key_contact_name": "Helen Gordon",
            "key_contact_title": "Chief Executive",
        },
        {
            "name": "Quintain",
            "companies_house_number": "02767211",
            "sector": "BTR",
            "sub_sector": "Developer",
            "company_type": "Private",
            "website": "https://www.quintain.co.uk",
            "headquarters_address": "One Wembley Hill Road",
            "headquarters_postcode": "HA9 0WS",
            "employee_count": 250,
            "revenue_gbp": 200000000,
            "is_client": False,
            "is_competitor": False,
            "is_target": True,
            "relationship_status": "Prospecting",
            "key_contact_name": "James Saunders",
            "key_contact_title": "Chief Executive Officer",
        },
        {
            "name": "Essential Living",
            "companies_house_number": "08654321",
            "sector": "BTR",
            "sub_sector": "Operator",
            "company_type": "Private",
            "website": "https://www.essentialliving.co.uk",
            "headquarters_address": "25 Wilton Road, Victoria",
            "headquarters_postcode": "SW1V 1LW",
            "employee_count": 120,
            "revenue_gbp": 85000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": True,
            "relationship_status": "Cold",
            "key_contact_name": "Oliver Mayatt",
            "key_contact_title": "Director of Operations",
        },
        {
            "name": "Get Living",
            "companies_house_number": "09123456",
            "sector": "BTR",
            "sub_sector": "Operator",
            "company_type": "Private",
            "website": "https://www.getliving.com",
            "headquarters_address": "East Village, 7 Celebration Avenue",
            "headquarters_postcode": "E20 1DB",
            "employee_count": 200,
            "revenue_gbp": 150000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": True,
            "relationship_status": "Warm Lead",
            "key_contact_name": "Rick de Blaby",
            "key_contact_title": "Chief Executive",
        },
        {
            "name": "Fizzy Living",
            "companies_house_number": "07654321",
            "sector": "BTR",
            "sub_sector": "Operator",
            "company_type": "Private",
            "website": "https://www.fizzyliving.com",
            "headquarters_address": "Thames Tower, Station Road",
            "headquarters_postcode": "RG1 1LX",
            "employee_count": 80,
            "revenue_gbp": 45000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Cold",
            "key_contact_name": "Harry Downes",
            "key_contact_title": "Managing Director",
        },
        {
            "name": "Moda Living",
            "companies_house_number": "10234567",
            "sector": "BTR",
            "sub_sector": "Developer/Operator",
            "company_type": "Private",
            "website": "https://www.modaliving.com",
            "headquarters_address": "Bruntwood SciTech, Circle Square",
            "headquarters_postcode": "M1 7FS",
            "employee_count": 300,
            "revenue_gbp": 180000000,
            "is_client": True,
            "is_competitor": False,
            "is_target": False,
            "relationship_status": "Active Client",
            "key_contact_name": "Tony Brooks",
            "key_contact_title": "Founder and Chairman",
        },
        {
            "name": "Allsop",
            "companies_house_number": "00344685",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Private",
            "website": "https://www.allsop.co.uk",
            "headquarters_address": "33 Wigmore Street",
            "headquarters_postcode": "W1U 1BZ",
            "employee_count": 450,
            "revenue_gbp": 120000000,
            "is_client": True,
            "is_competitor": False,
            "is_target": False,
            "relationship_status": "Active Client",
            "key_contact_name": "Richard Holt",
            "key_contact_title": "Partner",
        },
        {
            "name": "Savills",
            "companies_house_number": "02122174",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Public",
            "website": "https://www.savills.co.uk",
            "headquarters_address": "33 Margaret Street",
            "headquarters_postcode": "W1G 0JD",
            "employee_count": 4500,
            "revenue_gbp": 2100000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Competitor",
            "key_contact_name": "Mark Ridley",
            "key_contact_title": "Group Chief Executive",
        },
        {
            "name": "JLL",
            "companies_house_number": "01188567",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Public",
            "website": "https://www.jll.co.uk",
            "headquarters_address": "30 Warwick Street",
            "headquarters_postcode": "W1B 5NH",
            "employee_count": 5000,
            "revenue_gbp": 2500000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Competitor",
            "key_contact_name": "Chris Ireland",
            "key_contact_title": "UK CEO",
        },
        {
            "name": "CBRE",
            "companies_house_number": "03536032",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Public",
            "website": "https://www.cbre.co.uk",
            "headquarters_address": "Henrietta House, Henrietta Place",
            "headquarters_postcode": "W1G 0NB",
            "employee_count": 6000,
            "revenue_gbp": 2800000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Competitor",
            "key_contact_name": "Ciaran Bird",
            "key_contact_title": "UK President",
        },
        {
            "name": "Knight Frank",
            "companies_house_number": "02508912",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Private",
            "website": "https://www.knightfrank.co.uk",
            "headquarters_address": "55 Baker Street",
            "headquarters_postcode": "W1U 8AN",
            "employee_count": 3800,
            "revenue_gbp": 1900000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Competitor",
            "key_contact_name": "William Beardmore-Gray",
            "key_contact_title": "Group Chairman",
        },
        {
            "name": "Cushman & Wakefield",
            "companies_house_number": "00616398",
            "sector": "Professional Services",
            "sub_sector": "Property Consultancy",
            "company_type": "Public",
            "website": "https://www.cushmanwakefield.com/en/united-kingdom",
            "headquarters_address": "125 Old Broad Street",
            "headquarters_postcode": "EC2N 1AR",
            "employee_count": 4200,
            "revenue_gbp": 2200000000,
            "is_client": False,
            "is_competitor": True,
            "is_target": False,
            "relationship_status": "Competitor",
            "key_contact_name": "Robert Sobel",
            "key_contact_title": "UK CEO",
        },
    ]

    companies = []
    for data in companies_data:
        company = Company(**data)
        session.add(company)
        companies.append(company)

    session.flush()
    print(f"  Seeded {len(companies)} companies.")
    return companies


def seed_planning_applications(
    session: Session,
    councils: list[Council],
    companies: list[Company],
) -> list[PlanningApplication]:
    """Seed 20+ realistic planning applications."""
    print("Seeding planning applications...")

    # Helper to find council/company by name
    council_map = {c.name: c for c in councils}
    company_map = {c.name: c for c in companies}

    applications_data = [
        {
            "council_id": council_map["London Borough of Tower Hamlets"].id,
            "reference": "PA/24/01234/A1",
            "description": "Demolition of existing warehouse and erection of a 32-storey building comprising 450 Build to Rent residential units (Use Class C3) with ground floor commercial space (Use Class E), associated car parking, cycle storage, landscaping and amenity space",
            "address": "Former Goodmans Fields, 72-86 Leman Street, London",
            "postcode": "E1 8EU",
            "ward": "Whitechapel",
            "applicant_name": "Greystar Real Estate Partners",
            "applicant_company_id": company_map["Greystar"].id,
            "agent_name": "DP9 Ltd",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2025, 11, 15),
            "validated_date": date(2025, 11, 20),
            "total_units": 450,
            "affordable_units": 158,
            "commercial_sqm": 2500.0,
            "storeys": 32,
            "latitude": 51.5138,
            "longitude": -0.0685,
            "is_btr": True,
            "bd_relevance_score": 9.5,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Manchester City Council"].id,
            "reference": "134567/FO/2025",
            "description": "Erection of two residential towers of 38 and 44 storeys providing 756 apartments for Build to Rent, with ancillary resident amenities, co-working space, ground floor retail units and basement car parking",
            "address": "Plot C2, New Town Development, Great Ancoats Street, Manchester",
            "postcode": "M4 5AZ",
            "ward": "Ancoats & Beswick",
            "applicant_name": "Moda Living Ltd",
            "applicant_company_id": company_map["Moda Living"].id,
            "agent_name": "Deloitte Real Estate",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 9, 12),
            "submitted_date": date(2025, 3, 1),
            "validated_date": date(2025, 3, 8),
            "total_units": 756,
            "affordable_units": 151,
            "commercial_sqm": 3200.0,
            "storeys": 44,
            "latitude": 53.4842,
            "longitude": -2.2308,
            "is_btr": True,
            "bd_relevance_score": 9.8,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Birmingham City Council"].id,
            "reference": "2025/04567/PA",
            "description": "Purpose built student accommodation comprising 680 bed spaces in a 22-storey tower with ground floor commercial units, communal study areas, gym and roof terrace",
            "address": "Site of Former Eagle & Tun Public House, 175 Banbury Street, Digbeth",
            "postcode": "B5 5TH",
            "ward": "Bordesley & Highgate",
            "applicant_name": "Unite Students Group Ltd",
            "applicant_company_id": company_map["Unite Students"].id,
            "agent_name": "Turley Associates",
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Under Consideration",
            "submitted_date": date(2025, 12, 1),
            "validated_date": date(2025, 12, 10),
            "total_units": 680,
            "storeys": 22,
            "latitude": 52.4730,
            "longitude": -1.8870,
            "is_pbsa": True,
            "bd_relevance_score": 8.5,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Leeds City Council"].id,
            "reference": "25/02345/FU",
            "description": "Mixed-use development comprising 520 Build to Rent apartments in two towers of 28 and 20 storeys, with 1,200 sqm of ground floor commercial space, residents lounge, gym, and 200 cycle spaces",
            "address": "Former Tetley Brewery Site, Hunslet Road",
            "postcode": "LS10 1JQ",
            "ward": "Hunslet & Riverside",
            "applicant_name": "Legal & General Investment Management",
            "applicant_company_id": company_map["Legal & General"].id,
            "agent_name": "Quod Planning",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Pending Decision",
            "submitted_date": date(2025, 8, 15),
            "validated_date": date(2025, 8, 22),
            "consultation_end_date": date(2025, 10, 1),
            "total_units": 520,
            "affordable_units": 104,
            "commercial_sqm": 1200.0,
            "storeys": 28,
            "latitude": 53.7896,
            "longitude": -1.5380,
            "is_btr": True,
            "bd_relevance_score": 9.2,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Hackney"].id,
            "reference": "2025/1567",
            "description": "Conversion and extension of existing office building to provide 185 co-living units (Sui Generis) with shared amenity space, communal kitchen and dining areas, roof garden and cycle storage",
            "address": "Hackney Central House, 27-35 Mare Street",
            "postcode": "E8 4RP",
            "ward": "Hackney Central",
            "applicant_name": "The Collective",
            "application_type": "Full Planning Application",
            "scheme_type": "Co-Living",
            "status": "Under Consideration",
            "submitted_date": date(2025, 10, 5),
            "validated_date": date(2025, 10, 12),
            "total_units": 185,
            "storeys": 12,
            "latitude": 51.5452,
            "longitude": -0.0553,
            "is_btr": False,
            "bd_relevance_score": 7.0,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Bristol City Council"].id,
            "reference": "25/01890/F",
            "description": "Erection of a 16-storey building providing 310 purpose-built student bedrooms, with ground floor cafe/retail space, communal study areas, laundry facilities and associated landscaping",
            "address": "Temple Island, Temple Gate",
            "postcode": "BS1 6QA",
            "ward": "Central",
            "applicant_name": "Unite Group PLC",
            "applicant_company_id": company_map["Unite Students"].id,
            "agent_name": "Savills Planning",
            "agent_company_id": company_map["Savills"].id,
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 7, 20),
            "submitted_date": date(2025, 2, 10),
            "validated_date": date(2025, 2, 17),
            "total_units": 310,
            "storeys": 16,
            "latitude": 51.4480,
            "longitude": -2.5835,
            "is_pbsa": True,
            "bd_relevance_score": 8.0,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Southwark"].id,
            "reference": "25/AP/0456",
            "description": "Redevelopment of the site to provide a mixed-use scheme comprising 380 residential units (Build to Rent), 850 sqm commercial floorspace (Use Class E), new public realm and landscaping",
            "address": "Land at 100-108 Old Kent Road",
            "postcode": "SE1 5AG",
            "ward": "Old Kent Road",
            "applicant_name": "Grainger PLC",
            "applicant_company_id": company_map["Grainger PLC"].id,
            "agent_name": "Gerald Eve LLP",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2025, 6, 20),
            "validated_date": date(2025, 6, 28),
            "total_units": 380,
            "affordable_units": 133,
            "commercial_sqm": 850.0,
            "storeys": 25,
            "latitude": 51.4870,
            "longitude": -0.0780,
            "is_btr": True,
            "bd_relevance_score": 9.0,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Salford City Council"].id,
            "reference": "25/78901/FUL",
            "description": "Erection of a 50-storey residential tower comprising 550 Build to Rent apartments with ground floor commercial space, resident amenities including gym, cinema room, co-working and roof terrace",
            "address": "Plot B5, Greengate, New Bailey Street",
            "postcode": "M3 5FS",
            "ward": "Blackfriars & Trinity",
            "applicant_name": "Get Living Ltd",
            "applicant_company_id": company_map["Get Living"].id,
            "agent_name": "DPP Planning",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Committee Decision",
            "submitted_date": date(2025, 4, 10),
            "validated_date": date(2025, 4, 15),
            "committee_date": date(2026, 1, 15),
            "total_units": 550,
            "affordable_units": 110,
            "commercial_sqm": 1800.0,
            "storeys": 50,
            "latitude": 53.4851,
            "longitude": -2.2503,
            "is_btr": True,
            "bd_relevance_score": 9.3,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Newham"].id,
            "reference": "25/00345/FUL",
            "description": "Construction of 3 residential buildings ranging from 12 to 26 storeys providing 420 homes for Build to Rent with communal amenity space, commercial units at ground floor, new public square and associated infrastructure",
            "address": "Silvertown Quays, North Woolwich Road",
            "postcode": "E16 2AB",
            "ward": "Royal Docks",
            "applicant_name": "Quintain Ltd",
            "applicant_company_id": company_map["Quintain"].id,
            "agent_name": "CBRE Planning",
            "agent_company_id": company_map["CBRE"].id,
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 11, 30),
            "submitted_date": date(2025, 5, 10),
            "validated_date": date(2025, 5, 18),
            "total_units": 420,
            "affordable_units": 210,
            "commercial_sqm": 2100.0,
            "storeys": 26,
            "latitude": 51.5055,
            "longitude": 0.0301,
            "is_btr": True,
            "bd_relevance_score": 8.8,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Nottingham City Council"].id,
            "reference": "25/01234/PFUL3",
            "description": "Development of purpose-built student accommodation comprising 450 bed spaces in a cluster flat arrangement, with ground floor communal facilities, gym and courtyard garden",
            "address": "Castle Wharf, Canal Street",
            "postcode": "NG1 7EH",
            "ward": "Castle",
            "applicant_name": "Crosslane Student Developments",
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Under Consideration",
            "submitted_date": date(2026, 1, 8),
            "validated_date": date(2026, 1, 15),
            "total_units": 450,
            "storeys": 14,
            "latitude": 52.9491,
            "longitude": -1.1533,
            "is_pbsa": True,
            "bd_relevance_score": 7.5,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["City of Edinburgh Council"].id,
            "reference": "25/04567/FUL",
            "description": "Erection of mixed-use development comprising 290 Build to Rent apartments, 120 PBSA bed spaces, ground floor retail and commercial space, new public realm and 150 cycle spaces",
            "address": "Fountainbridge Site, Dundee Street",
            "postcode": "EH11 1AF",
            "ward": "Fountainbridge/Craiglockhart",
            "applicant_name": "Moda Living Ltd",
            "applicant_company_id": company_map["Moda Living"].id,
            "agent_name": "JLL Planning",
            "agent_company_id": company_map["JLL"].id,
            "application_type": "Planning Permission in Principle",
            "scheme_type": "Mixed BTR/PBSA",
            "status": "Under Consideration",
            "submitted_date": date(2025, 9, 20),
            "validated_date": date(2025, 9, 28),
            "total_units": 410,
            "commercial_sqm": 1500.0,
            "storeys": 18,
            "latitude": 55.9411,
            "longitude": -3.2120,
            "is_btr": True,
            "is_pbsa": True,
            "bd_relevance_score": 9.1,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Newcastle City Council"].id,
            "reference": "2025/1890/01/DET",
            "description": "Demolition of existing buildings and construction of 340 Build to Rent apartments in a 22-storey tower with podium building, residents gym, lounge, terrace and 80 car parking spaces",
            "address": "Forth Banks, Forth Street",
            "postcode": "NE1 3PJ",
            "ward": "Westgate",
            "applicant_name": "Grainger PLC",
            "applicant_company_id": company_map["Grainger PLC"].id,
            "agent_name": "Knight Frank Planning",
            "agent_company_id": company_map["Knight Frank"].id,
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 12, 5),
            "submitted_date": date(2025, 6, 1),
            "validated_date": date(2025, 6, 8),
            "total_units": 340,
            "affordable_units": 51,
            "storeys": 22,
            "latitude": 54.9668,
            "longitude": -1.6268,
            "is_btr": True,
            "bd_relevance_score": 8.5,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Lambeth"].id,
            "reference": "25/01234/FUL",
            "description": "Comprehensive redevelopment to provide 280 residential units across three buildings ranging from 8 to 18 storeys, with affordable housing, commercial space, new public realm and landscaping",
            "address": "65-69 Effra Road, Brixton",
            "postcode": "SW2 1BZ",
            "ward": "Brixton Hill",
            "applicant_name": "Essential Living Ltd",
            "applicant_company_id": company_map["Essential Living"].id,
            "agent_name": "Montagu Evans LLP",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2026, 2, 1),
            "validated_date": date(2026, 2, 8),
            "total_units": 280,
            "affordable_units": 98,
            "commercial_sqm": 600.0,
            "storeys": 18,
            "latitude": 51.4575,
            "longitude": -0.1110,
            "is_btr": True,
            "bd_relevance_score": 8.8,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Sheffield City Council"].id,
            "reference": "25/01567/FUL",
            "description": "Erection of 15-storey building comprising 220 purpose-built student accommodation bed spaces with communal study, social and amenity spaces, ground floor commercial unit and cycle storage",
            "address": "135-149 West Street",
            "postcode": "S1 4EQ",
            "ward": "City",
            "applicant_name": "Watkin Jones Group",
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Pending Decision",
            "submitted_date": date(2025, 7, 12),
            "validated_date": date(2025, 7, 19),
            "total_units": 220,
            "storeys": 15,
            "latitude": 53.3830,
            "longitude": -1.4763,
            "is_pbsa": True,
            "bd_relevance_score": 7.8,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Greenwich"].id,
            "reference": "25/1456/F",
            "description": "Mixed-use redevelopment of the site providing 600 homes including 350 Build to Rent units and 250 affordable homes, commercial floorspace, a primary school and new public open space",
            "address": "Woolwich Estates, Plumstead Road",
            "postcode": "SE18 7BZ",
            "ward": "Woolwich Common",
            "applicant_name": "Peabody Group / Berkeley Homes",
            "agent_name": "Savills Planning",
            "agent_company_id": company_map["Savills"].id,
            "application_type": "Outline Planning Application",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2025, 11, 1),
            "validated_date": date(2025, 11, 10),
            "total_units": 600,
            "affordable_units": 250,
            "commercial_sqm": 4500.0,
            "storeys": 30,
            "latitude": 51.4860,
            "longitude": 0.0631,
            "is_btr": True,
            "is_affordable": True,
            "bd_relevance_score": 8.2,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Glasgow City Council"].id,
            "reference": "25/01234/DC",
            "description": "Formation of residential development comprising 480 Build to Rent apartments in two buildings of 20 and 28 storeys with ground floor commercial units, residents amenity space, and associated landscaping",
            "address": "Buchanan Wharf, Port Dundas Road",
            "postcode": "G4 9SS",
            "ward": "Canal",
            "applicant_name": "Drum Property Group / Invesco",
            "agent_name": "Cushman & Wakefield",
            "agent_company_id": company_map["Cushman & Wakefield"].id,
            "application_type": "Full Planning Permission",
            "scheme_type": "BTR",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 10, 18),
            "submitted_date": date(2025, 4, 5),
            "validated_date": date(2025, 4, 12),
            "total_units": 480,
            "affordable_units": 120,
            "commercial_sqm": 2000.0,
            "storeys": 28,
            "latitude": 55.8681,
            "longitude": -4.2551,
            "is_btr": True,
            "bd_relevance_score": 8.9,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Brighton and Hove City Council"].id,
            "reference": "BH2025/02345",
            "description": "Demolition of existing retail warehouse and erection of mixed-use development comprising 195 Build to Rent residential units, flexible commercial space, public realm improvements and associated works",
            "address": "Former Toys R Us Site, Western Road, Hove",
            "postcode": "BN3 1JD",
            "ward": "Brunswick & Adelaide",
            "applicant_name": "Fizzy Living Ltd",
            "applicant_company_id": company_map["Fizzy Living"].id,
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Refused",
            "decision": "Refused",
            "decision_date": date(2025, 8, 14),
            "submitted_date": date(2025, 1, 20),
            "validated_date": date(2025, 1, 27),
            "total_units": 195,
            "affordable_units": 78,
            "commercial_sqm": 450.0,
            "storeys": 10,
            "latitude": 50.8299,
            "longitude": -0.1651,
            "is_btr": True,
            "bd_relevance_score": 6.5,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Cambridge City Council"].id,
            "reference": "25/0890/FUL",
            "description": "Erection of 350 purpose-built student accommodation bed spaces in buildings ranging from 4 to 8 storeys with communal facilities, courtyard garden and 350 cycle parking spaces",
            "address": "Land north of Newmarket Road",
            "postcode": "CB5 8DT",
            "ward": "Abbey",
            "applicant_name": "Unite Students Group Ltd",
            "applicant_company_id": company_map["Unite Students"].id,
            "agent_name": "Carter Jonas",
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Approved",
            "decision": "Granted",
            "decision_date": date(2025, 5, 30),
            "submitted_date": date(2024, 11, 5),
            "validated_date": date(2024, 11, 12),
            "total_units": 350,
            "storeys": 8,
            "latitude": 52.2070,
            "longitude": 0.1399,
            "is_pbsa": True,
            "bd_relevance_score": 8.0,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Liverpool City Council"].id,
            "reference": "25F/1234",
            "description": "Construction of a 35-storey residential tower providing 400 Build to Rent apartments with ancillary communal space, ground floor restaurant/cafe, resident parking and public realm works",
            "address": "Plot 6, Liverpool Waters, Princes Dock",
            "postcode": "L3 1DL",
            "ward": "Kirkdale",
            "applicant_name": "Peel L&P / Moda Living",
            "applicant_company_id": company_map["Moda Living"].id,
            "agent_name": "Turley Planning",
            "application_type": "Reserved Matters",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2026, 1, 15),
            "validated_date": date(2026, 1, 22),
            "total_units": 400,
            "affordable_units": 80,
            "commercial_sqm": 900.0,
            "storeys": 35,
            "latitude": 53.4105,
            "longitude": -2.9914,
            "is_btr": True,
            "bd_relevance_score": 9.0,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["London Borough of Wandsworth"].id,
            "reference": "2025/5678",
            "description": "Hybrid planning application for phased mixed-use development comprising up to 1,200 residential units (including 500 BTR), commercial, retail, community space, new park, and associated infrastructure",
            "address": "Wandsworth Gasworks, Ram Quarter Phase 2, Ram Street",
            "postcode": "SW18 1TQ",
            "ward": "Wandsworth Town",
            "applicant_name": "Greencoat Capital / Frasers Property",
            "agent_name": "JLL Planning",
            "agent_company_id": company_map["JLL"].id,
            "application_type": "Hybrid Planning Application",
            "scheme_type": "BTR",
            "status": "Under Consideration",
            "submitted_date": date(2025, 10, 20),
            "validated_date": date(2025, 10, 28),
            "total_units": 1200,
            "affordable_units": 396,
            "commercial_sqm": 8500.0,
            "storeys": 40,
            "latitude": 51.4580,
            "longitude": -0.1880,
            "is_btr": True,
            "bd_relevance_score": 9.7,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Reading Borough Council"].id,
            "reference": "250123/FUL",
            "description": "Demolition of existing office buildings and erection of two residential buildings of 14 and 8 storeys providing 240 Build to Rent apartments with landscaped courtyard, residents lounge and gym",
            "address": "Former Scottish & Southern Energy HQ, Vastern Road",
            "postcode": "RG1 8DB",
            "ward": "Abbey",
            "applicant_name": "Grainger PLC",
            "applicant_company_id": company_map["Grainger PLC"].id,
            "agent_name": "Barton Willmore (now Stantec)",
            "application_type": "Full Planning Application",
            "scheme_type": "BTR",
            "status": "Pending Decision",
            "submitted_date": date(2025, 12, 5),
            "validated_date": date(2025, 12, 12),
            "total_units": 240,
            "affordable_units": 72,
            "storeys": 14,
            "latitude": 51.4589,
            "longitude": -0.9718,
            "is_btr": True,
            "bd_relevance_score": 7.8,
            "source": "idox_scraper",
        },
        {
            "council_id": council_map["Leicester City Council"].id,
            "reference": "20250456",
            "description": "Erection of 16-storey building comprising 380 purpose-built student accommodation bed spaces with ground floor retail unit, communal study space, gym, laundry and external courtyard",
            "address": "Land at Vaughan Way / Burley's Way",
            "postcode": "LE1 4SQ",
            "ward": "Castle",
            "applicant_name": "Student Roost / GSA",
            "application_type": "Full Planning Application",
            "scheme_type": "PBSA",
            "status": "Under Consideration",
            "submitted_date": date(2026, 2, 20),
            "validated_date": date(2026, 2, 28),
            "total_units": 380,
            "storeys": 16,
            "latitude": 52.6375,
            "longitude": -1.1334,
            "is_pbsa": True,
            "bd_relevance_score": 7.2,
            "source": "idox_scraper",
        },
    ]

    applications = []
    for data in applications_data:
        app = PlanningApplication(**data)
        session.add(app)
        applications.append(app)

    session.flush()
    print(f"  Seeded {len(applications)} planning applications.")
    return applications


def seed_schemes(
    session: Session,
    councils: list[Council],
    companies: list[Company],
) -> list[Scheme]:
    """Seed 15+ existing/operational schemes."""
    print("Seeding schemes...")

    council_map = {c.name: c for c in councils}
    company_map = {c.name: c for c in companies}

    schemes_data = [
        {
            "name": "The Collective Canary Wharf",
            "address": "20 Crossharbour Plaza, London",
            "postcode": "E14 9YF",
            "council_id": council_map["London Borough of Tower Hamlets"].id,
            "operator_company_id": company_map["Greystar"].id,
            "scheme_type": "Co-Living",
            "status": "Operational",
            "total_units": 705,
            "unit_mix": {"studio": 450, "1bed": 200, "2bed": 55},
            "amenities": ["gym", "co-working", "cinema", "roof terrace", "restaurant", "laundry"],
            "completion_date": date(2020, 9, 1),
            "contract_start_date": date(2022, 1, 1),
            "contract_end_date": date(2027, 12, 31),
            "contract_type": "Management Agreement",
            "annual_revenue_gbp": 18500000,
            "occupancy_pct": 94.5,
            "avg_rent_pcm": 1850.0,
            "performance_rating": 4.2,
            "nps_score": 42.0,
            "latitude": 51.4975,
            "longitude": -0.0150,
        },
        {
            "name": "East Village E20",
            "address": "7 Celebration Avenue, London",
            "postcode": "E20 1DB",
            "council_id": council_map["London Borough of Newham"].id,
            "owner_company_id": company_map["Get Living"].id,
            "operator_company_id": company_map["Get Living"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 1439,
            "unit_mix": {"1bed": 520, "2bed": 630, "3bed": 220, "4bed": 69},
            "amenities": ["gym", "concierge", "gardens", "play areas", "bike storage"],
            "completion_date": date(2013, 8, 1),
            "contract_start_date": date(2013, 8, 1),
            "contract_end_date": date(2028, 7, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 38000000,
            "occupancy_pct": 97.2,
            "avg_rent_pcm": 1650.0,
            "performance_rating": 4.5,
            "nps_score": 55.0,
            "latitude": 51.5460,
            "longitude": -0.0130,
        },
        {
            "name": "Vox Manchester",
            "address": "58 Jersey Street, Ancoats, Manchester",
            "postcode": "M4 6JE",
            "council_id": council_map["Manchester City Council"].id,
            "operator_company_id": company_map["Grainger PLC"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 294,
            "unit_mix": {"studio": 45, "1bed": 150, "2bed": 85, "3bed": 14},
            "amenities": ["gym", "co-working", "residents lounge", "roof terrace", "concierge"],
            "completion_date": date(2022, 3, 1),
            "contract_start_date": date(2022, 3, 1),
            "contract_end_date": date(2027, 2, 28),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 5800000,
            "occupancy_pct": 96.1,
            "avg_rent_pcm": 1250.0,
            "performance_rating": 4.3,
            "nps_score": 48.0,
            "latitude": 53.4838,
            "longitude": -2.2270,
        },
        {
            "name": "The Copper House, Battersea",
            "address": "1 Copper House Court, Battersea, London",
            "postcode": "SW11 2FZ",
            "council_id": council_map["London Borough of Wandsworth"].id,
            "operator_company_id": company_map["Fizzy Living"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 172,
            "unit_mix": {"studio": 30, "1bed": 90, "2bed": 42, "3bed": 10},
            "amenities": ["gym", "residents lounge", "roof terrace", "bike storage"],
            "completion_date": date(2019, 6, 1),
            "contract_start_date": date(2019, 6, 1),
            "contract_end_date": date(2026, 5, 31),
            "contract_type": "Management Agreement",
            "annual_revenue_gbp": 4200000,
            "occupancy_pct": 95.3,
            "avg_rent_pcm": 1980.0,
            "performance_rating": 4.0,
            "nps_score": 38.0,
            "latitude": 51.4710,
            "longitude": -0.1730,
        },
        {
            "name": "Angel Gardens, Manchester",
            "address": "7 Charter Street, Manchester",
            "postcode": "M3 7AH",
            "council_id": council_map["Manchester City Council"].id,
            "operator_company_id": company_map["Moda Living"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 466,
            "unit_mix": {"studio": 80, "1bed": 230, "2bed": 130, "3bed": 26},
            "amenities": ["gym", "co-working", "cinema", "sky lounge", "residents garden", "concierge"],
            "completion_date": date(2020, 12, 1),
            "contract_start_date": date(2020, 12, 1),
            "contract_end_date": date(2030, 11, 30),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 9200000,
            "occupancy_pct": 97.5,
            "avg_rent_pcm": 1350.0,
            "performance_rating": 4.7,
            "nps_score": 62.0,
            "latitude": 53.4877,
            "longitude": -2.2420,
        },
        {
            "name": "Wembley Park Quintain BTR",
            "address": "Olympic Way, Wembley Park, London",
            "postcode": "HA9 0GU",
            "council_id": council_map["London Borough of Ealing"].id,
            "owner_company_id": company_map["Quintain"].id,
            "operator_company_id": company_map["Quintain"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 3000,
            "unit_mix": {"studio": 500, "1bed": 1200, "2bed": 900, "3bed": 400},
            "amenities": ["gym", "pool", "co-working", "cinema", "roof gardens", "concierge", "residents events"],
            "completion_date": date(2023, 6, 1),
            "contract_start_date": date(2018, 1, 1),
            "contract_end_date": date(2033, 12, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 62000000,
            "occupancy_pct": 93.8,
            "avg_rent_pcm": 1750.0,
            "performance_rating": 4.1,
            "nps_score": 40.0,
            "latitude": 51.5583,
            "longitude": -0.2812,
        },
        {
            "name": "Clippers Quay, Salford",
            "address": "1 Exchange Quay, Salford Quays",
            "postcode": "M5 3EQ",
            "council_id": council_map["Salford City Council"].id,
            "operator_company_id": company_map["Grainger PLC"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 614,
            "unit_mix": {"studio": 90, "1bed": 300, "2bed": 180, "3bed": 44},
            "amenities": ["gym", "co-working", "residents lounge", "courtyard gardens", "concierge"],
            "completion_date": date(2020, 9, 1),
            "contract_start_date": date(2020, 9, 1),
            "contract_end_date": date(2025, 8, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 10500000,
            "occupancy_pct": 98.0,
            "avg_rent_pcm": 1150.0,
            "performance_rating": 4.4,
            "nps_score": 50.0,
            "latitude": 53.4700,
            "longitude": -2.2860,
        },
        {
            "name": "The Lexicon, City Road, London",
            "address": "261 City Road, London",
            "postcode": "EC1V 1LA",
            "council_id": council_map["London Borough of Islington"].id,
            "operator_company_id": company_map["Essential Living"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 307,
            "unit_mix": {"studio": 55, "1bed": 160, "2bed": 75, "3bed": 17},
            "amenities": ["gym", "cinema", "residents lounge", "roof terrace", "concierge"],
            "completion_date": date(2018, 11, 1),
            "contract_start_date": date(2018, 11, 1),
            "contract_end_date": date(2026, 10, 31),
            "contract_type": "Management Agreement",
            "annual_revenue_gbp": 7800000,
            "occupancy_pct": 96.5,
            "avg_rent_pcm": 2100.0,
            "performance_rating": 3.9,
            "nps_score": 35.0,
            "latitude": 51.5290,
            "longitude": -0.0913,
        },
        {
            "name": "Unite Students - Moonraker Point",
            "address": "Pocock Street, Southwark, London",
            "postcode": "SE1 0BG",
            "council_id": council_map["London Borough of Southwark"].id,
            "owner_company_id": company_map["Unite Students"].id,
            "operator_company_id": company_map["Unite Students"].id,
            "scheme_type": "PBSA",
            "status": "Operational",
            "total_units": 580,
            "unit_mix": {"en_suite": 400, "studio": 150, "twodio": 30},
            "amenities": ["common room", "study rooms", "gym", "laundry", "bike storage"],
            "completion_date": date(2017, 9, 1),
            "contract_start_date": date(2017, 9, 1),
            "contract_end_date": date(2032, 8, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 12000000,
            "occupancy_pct": 99.0,
            "avg_rent_pcm": 1200.0,
            "performance_rating": 4.6,
            "nps_score": 52.0,
            "latitude": 51.4990,
            "longitude": -0.1020,
        },
        {
            "name": "The Lofts, Newcastle",
            "address": "Forth Banks, Newcastle upon Tyne",
            "postcode": "NE1 3PJ",
            "council_id": council_map["Newcastle City Council"].id,
            "operator_company_id": company_map["Grainger PLC"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 160,
            "unit_mix": {"1bed": 85, "2bed": 60, "3bed": 15},
            "amenities": ["gym", "residents lounge", "bike storage", "concierge"],
            "completion_date": date(2021, 4, 1),
            "contract_start_date": date(2021, 4, 1),
            "contract_end_date": date(2026, 3, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 2400000,
            "occupancy_pct": 95.0,
            "avg_rent_pcm": 950.0,
            "performance_rating": 4.2,
            "nps_score": 45.0,
            "latitude": 54.9668,
            "longitude": -1.6268,
        },
        {
            "name": "UNCLE Leeds",
            "address": "6-12 Whitehall Road, Leeds",
            "postcode": "LS1 4AW",
            "council_id": council_map["Leeds City Council"].id,
            "operator_company_id": company_map["Moda Living"].id,
            "scheme_type": "BTR",
            "status": "Lease-Up",
            "total_units": 515,
            "unit_mix": {"studio": 80, "1bed": 260, "2bed": 145, "3bed": 30},
            "amenities": ["gym", "co-working", "cinema room", "sky lounge", "concierge", "parcel room"],
            "completion_date": date(2025, 6, 1),
            "contract_start_date": date(2025, 6, 1),
            "contract_end_date": date(2035, 5, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 8500000,
            "occupancy_pct": 65.0,
            "avg_rent_pcm": 1100.0,
            "performance_rating": 4.3,
            "nps_score": 50.0,
            "latitude": 53.7945,
            "longitude": -1.5556,
        },
        {
            "name": "Apo Birmingham",
            "address": "9 Dartmouth Middleway, Highgate, Birmingham",
            "postcode": "B7 4AU",
            "council_id": council_map["Birmingham City Council"].id,
            "operator_company_id": company_map["Greystar"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 342,
            "unit_mix": {"studio": 70, "1bed": 170, "2bed": 85, "3bed": 17},
            "amenities": ["gym", "co-working", "residents lounge", "rooftop terrace", "concierge"],
            "completion_date": date(2023, 3, 1),
            "contract_start_date": date(2023, 3, 1),
            "contract_end_date": date(2028, 2, 28),
            "contract_type": "Management Agreement",
            "annual_revenue_gbp": 5600000,
            "occupancy_pct": 92.0,
            "avg_rent_pcm": 1050.0,
            "performance_rating": 4.0,
            "nps_score": 38.0,
            "latitude": 52.4755,
            "longitude": -1.8810,
        },
        {
            "name": "Edinburgh Fountainbridge PBSA",
            "address": "83 Fountainbridge, Edinburgh",
            "postcode": "EH3 9QA",
            "council_id": council_map["City of Edinburgh Council"].id,
            "owner_company_id": company_map["Unite Students"].id,
            "operator_company_id": company_map["Unite Students"].id,
            "scheme_type": "PBSA",
            "status": "Operational",
            "total_units": 440,
            "unit_mix": {"en_suite": 300, "studio": 120, "twodio": 20},
            "amenities": ["common room", "study rooms", "gym", "laundry", "cinema room"],
            "completion_date": date(2019, 9, 1),
            "contract_start_date": date(2019, 9, 1),
            "contract_end_date": date(2029, 8, 31),
            "contract_type": "Direct Operation",
            "annual_revenue_gbp": 8200000,
            "occupancy_pct": 98.5,
            "avg_rent_pcm": 980.0,
            "performance_rating": 4.5,
            "nps_score": 54.0,
            "latitude": 55.9411,
            "longitude": -3.2120,
        },
        {
            "name": "Greengate, Salford - L&G BTR",
            "address": "1 Greengate, Salford",
            "postcode": "M3 7NB",
            "council_id": council_map["Salford City Council"].id,
            "owner_company_id": company_map["Legal & General"].id,
            "scheme_type": "BTR",
            "status": "Under Construction",
            "total_units": 498,
            "unit_mix": {"studio": 60, "1bed": 250, "2bed": 150, "3bed": 38},
            "amenities": ["gym", "co-working", "residents lounge", "roof terrace", "concierge", "cinema room"],
            "completion_date": date(2027, 3, 1),
            "contract_start_date": date(2027, 3, 1),
            "contract_end_date": date(2037, 2, 28),
            "contract_type": "Management Agreement",
            "occupancy_pct": 0.0,
            "performance_rating": None,
            "latitude": 53.4854,
            "longitude": -2.2505,
        },
        {
            "name": "Mustard Wharf, Leeds",
            "address": "Mustard Wharf, Hunslet Road, Leeds",
            "postcode": "LS10 1FJ",
            "council_id": council_map["Leeds City Council"].id,
            "owner_company_id": company_map["Legal & General"].id,
            "scheme_type": "BTR",
            "status": "Operational",
            "total_units": 322,
            "unit_mix": {"1bed": 160, "2bed": 130, "3bed": 32},
            "amenities": ["gym", "co-working", "residents lounge", "roof terrace", "concierge"],
            "completion_date": date(2023, 9, 1),
            "contract_start_date": date(2023, 9, 1),
            "contract_end_date": date(2033, 8, 31),
            "contract_type": "Management Agreement",
            "annual_revenue_gbp": 5400000,
            "occupancy_pct": 94.0,
            "avg_rent_pcm": 1200.0,
            "performance_rating": 4.4,
            "nps_score": 48.0,
            "latitude": 53.7893,
            "longitude": -1.5407,
        },
    ]

    schemes = []
    for data in schemes_data:
        scheme = Scheme(**data)
        session.add(scheme)
        schemes.append(scheme)

    session.flush()
    print(f"  Seeded {len(schemes)} schemes.")
    return schemes


def seed_pipeline_opportunities(
    session: Session,
    applications: list[PlanningApplication],
    companies: list[Company],
    councils: list[Council],
) -> list[PipelineOpportunity]:
    """Seed pipeline opportunities."""
    print("Seeding pipeline opportunities...")

    company_map = {c.name: c for c in companies}
    council_map = {c.name: c for c in councils}

    opportunities_data = [
        {
            "title": "Greystar Tower Hamlets BTR - Management Pitch",
            "description": "450-unit BTR scheme at Goodmans Fields. Greystar seeking third-party operator. Submit management proposal by Q2 2026.",
            "planning_application_id": applications[0].id,
            "company_id": company_map["Greystar"].id,
            "council_id": council_map["London Borough of Tower Hamlets"].id,
            "source": "Planning Application",
            "stage": "Proposal",
            "priority": "High",
            "estimated_units": 450,
            "estimated_value_gbp": 12000000,
            "expected_start_date": date(2028, 6, 1),
            "expected_completion_date": date(2030, 6, 1),
            "probability_pct": 25.0,
            "assigned_to": "Sarah Chen",
            "last_activity_date": date(2026, 3, 10),
            "next_action": "Prepare management proposal and fee structure",
            "next_action_date": date(2026, 4, 15),
        },
        {
            "title": "Moda Manchester Phase 2 - Operational Support",
            "description": "756 units at New Town Development. Moda may require additional operational support for Phase 2 launch.",
            "planning_application_id": applications[1].id,
            "company_id": company_map["Moda Living"].id,
            "council_id": council_map["Manchester City Council"].id,
            "source": "Existing Client",
            "stage": "Negotiation",
            "priority": "High",
            "estimated_units": 756,
            "estimated_value_gbp": 8500000,
            "expected_start_date": date(2027, 9, 1),
            "probability_pct": 65.0,
            "assigned_to": "James Porter",
            "last_activity_date": date(2026, 3, 18),
            "next_action": "Follow up on commercial terms with Moda ops team",
            "next_action_date": date(2026, 3, 25),
        },
        {
            "title": "Grainger Southwark BTR - Advisory",
            "description": "380-unit scheme on Old Kent Road. Grainger exploring advisory relationship for operational setup.",
            "planning_application_id": applications[6].id,
            "company_id": company_map["Grainger PLC"].id,
            "council_id": council_map["London Borough of Southwark"].id,
            "source": "Planning Application",
            "stage": "Qualification",
            "priority": "Medium",
            "estimated_units": 380,
            "estimated_value_gbp": 3200000,
            "expected_start_date": date(2029, 1, 1),
            "probability_pct": 15.0,
            "assigned_to": "Sarah Chen",
            "last_activity_date": date(2026, 2, 20),
            "next_action": "Schedule intro meeting with Grainger development team",
            "next_action_date": date(2026, 4, 1),
        },
        {
            "title": "Get Living Salford Expansion",
            "description": "550-unit tower at Greengate. Get Living potential client for full management contract.",
            "planning_application_id": applications[7].id,
            "company_id": company_map["Get Living"].id,
            "council_id": council_map["Salford City Council"].id,
            "source": "Planning Application",
            "stage": "Lead",
            "priority": "High",
            "estimated_units": 550,
            "estimated_value_gbp": 6000000,
            "expected_start_date": date(2029, 6, 1),
            "probability_pct": 20.0,
            "assigned_to": "James Porter",
            "last_activity_date": date(2026, 1, 15),
            "next_action": "Research Get Living's current management structure",
            "next_action_date": date(2026, 3, 30),
        },
        {
            "title": "L&G Leeds Campus BTR - Contract Extension",
            "description": "Existing L&G BTR scheme at Mustard Wharf. Contract renewal discussion for extended management agreement.",
            "company_id": company_map["Legal & General"].id,
            "council_id": council_map["Leeds City Council"].id,
            "source": "Existing Client",
            "stage": "Negotiation",
            "priority": "Critical",
            "estimated_units": 322,
            "estimated_value_gbp": 5400000,
            "expected_start_date": date(2033, 9, 1),
            "probability_pct": 75.0,
            "assigned_to": "Sarah Chen",
            "last_activity_date": date(2026, 3, 20),
            "next_action": "Present renewal terms including performance incentive structure",
            "next_action_date": date(2026, 4, 5),
        },
        {
            "title": "Edinburgh BTR/PBSA Mixed Scheme",
            "description": "Moda Living 410-unit mixed BTR/PBSA development at Fountainbridge. Potential management mandate.",
            "planning_application_id": applications[10].id,
            "company_id": company_map["Moda Living"].id,
            "council_id": council_map["City of Edinburgh Council"].id,
            "source": "Planning Application",
            "stage": "Proposal",
            "priority": "Medium",
            "estimated_units": 410,
            "estimated_value_gbp": 4800000,
            "expected_start_date": date(2029, 1, 1),
            "probability_pct": 35.0,
            "assigned_to": "James Porter",
            "last_activity_date": date(2026, 3, 5),
            "next_action": "Prepare mixed-use management capability deck",
            "next_action_date": date(2026, 4, 10),
        },
        {
            "title": "Wandsworth Gasworks Major Scheme",
            "description": "1,200 unit hybrid scheme including 500 BTR. Early-stage developer engagement opportunity.",
            "planning_application_id": applications[19].id,
            "council_id": council_map["London Borough of Wandsworth"].id,
            "source": "Planning Application",
            "stage": "Lead",
            "priority": "Medium",
            "estimated_units": 500,
            "estimated_value_gbp": 15000000,
            "expected_start_date": date(2031, 1, 1),
            "probability_pct": 10.0,
            "assigned_to": "Sarah Chen",
            "last_activity_date": date(2026, 2, 15),
            "next_action": "Identify developer contacts and set up introductory call",
            "next_action_date": date(2026, 4, 20),
        },
    ]

    opportunities = []
    for data in opportunities_data:
        opp = PipelineOpportunity(**data)
        session.add(opp)
        opportunities.append(opp)

    session.flush()
    print(f"  Seeded {len(opportunities)} pipeline opportunities.")
    return opportunities


def seed_alerts(
    session: Session,
    applications: list[PlanningApplication],
    companies: list[Company],
    councils: list[Council],
    schemes: list[Scheme],
) -> list[Alert]:
    """Seed sample alerts."""
    print("Seeding alerts...")

    company_map = {c.name: c for c in companies}
    council_map = {c.name: c for c in councils}

    alerts_data = [
        {
            "title": "New 450-unit BTR application in Tower Hamlets",
            "message": "Greystar has submitted a major BTR application (PA/24/01234/A1) for 450 units at Goodmans Fields. This is a high-priority BD target.",
            "alert_type": "new_application",
            "severity": "high",
            "source": "planning_scraper",
            "planning_application_id": applications[0].id,
            "company_id": company_map["Greystar"].id,
            "council_id": council_map["London Borough of Tower Hamlets"].id,
            "is_read": True,
            "is_actioned": True,
            "actioned_by": "Sarah Chen",
            "actioned_at": datetime(2025, 11, 20, 14, 30),
        },
        {
            "title": "Moda Manchester application APPROVED",
            "message": "The 756-unit BTR scheme at New Town Development (134567/FO/2025) has been granted planning permission. Engage Moda re: operational support.",
            "alert_type": "status_change",
            "severity": "high",
            "source": "planning_scraper",
            "planning_application_id": applications[1].id,
            "company_id": company_map["Moda Living"].id,
            "council_id": council_map["Manchester City Council"].id,
            "is_read": True,
            "is_actioned": False,
        },
        {
            "title": "Brighton BTR application REFUSED",
            "message": "Fizzy Living's 195-unit BTR scheme at Western Road (BH2025/02345) has been refused. Monitor for appeal or revised submission.",
            "alert_type": "status_change",
            "severity": "medium",
            "source": "planning_scraper",
            "planning_application_id": applications[16].id,
            "company_id": company_map["Fizzy Living"].id,
            "council_id": council_map["Brighton and Hove City Council"].id,
            "is_read": False,
            "is_actioned": False,
        },
        {
            "title": "Clippers Quay contract expiring in 6 months",
            "message": "The management agreement for Clippers Quay (614 units, Salford) expires on 31 Aug 2025. Initiate renewal discussions with Grainger.",
            "alert_type": "contract_expiry",
            "severity": "critical",
            "source": "system",
            "company_id": company_map["Grainger PLC"].id,
            "scheme_id": schemes[6].id,
            "is_read": True,
            "is_actioned": True,
            "actioned_by": "James Porter",
            "actioned_at": datetime(2025, 3, 15, 10, 0),
        },
        {
            "title": "New PBSA application near existing scheme in Southwark",
            "message": "A new 580-bed PBSA application has been detected within 500m of the Unite Students Moonraker Point scheme. May impact student housing market dynamics.",
            "alert_type": "competitor_activity",
            "severity": "medium",
            "source": "planning_scraper",
            "council_id": council_map["London Borough of Southwark"].id,
            "scheme_id": schemes[8].id,
            "is_read": False,
            "is_actioned": False,
        },
        {
            "title": "Occupancy drop detected at Apo Birmingham",
            "message": "Occupancy at Apo Birmingham (Greystar) has fallen below 93% threshold. Current occupancy: 92.0%. Investigate market conditions and competitor activity.",
            "alert_type": "performance",
            "severity": "medium",
            "source": "system",
            "scheme_id": schemes[11].id,
            "company_id": company_map["Greystar"].id,
            "is_read": False,
            "is_actioned": False,
        },
        {
            "title": "Glasgow BTR scheme approved - 480 units",
            "message": "Drum Property/Invesco BTR scheme at Buchanan Wharf (480 units) has been approved. Potential third-party management opportunity.",
            "alert_type": "new_opportunity",
            "severity": "high",
            "source": "planning_scraper",
            "planning_application_id": applications[15].id,
            "council_id": council_map["Glasgow City Council"].id,
            "is_read": False,
            "is_actioned": False,
        },
        {
            "title": "L&G Greengate scheme - construction milestone",
            "message": "Legal & General's 498-unit BTR scheme at Greengate, Salford has reached topping-out. Management mobilisation planning should commence.",
            "alert_type": "milestone",
            "severity": "high",
            "source": "system",
            "company_id": company_map["Legal & General"].id,
            "scheme_id": schemes[13].id,
            "is_read": True,
            "is_actioned": False,
        },
    ]

    alerts = []
    for data in alerts_data:
        alert = Alert(**data)
        session.add(alert)
        alerts.append(alert)

    session.flush()
    print(f"  Seeded {len(alerts)} alerts.")
    return alerts


def seed_scraper_runs(
    session: Session,
    councils: list[Council],
) -> list[ScraperRun]:
    """Seed sample scraper runs."""
    print("Seeding scraper runs...")

    council_map = {c.name: c for c in councils}
    now = datetime(2026, 3, 22, 8, 0, 0)

    runs_data = [
        {
            "council_id": council_map["London Borough of Tower Hamlets"].id,
            "source": "idox_scraper",
            "status": "completed",
            "started_at": now - timedelta(hours=2),
            "completed_at": now - timedelta(hours=1, minutes=45),
            "records_found": 34,
            "records_created": 5,
            "records_updated": 12,
            "records_skipped": 17,
            "errors_count": 0,
            "duration_seconds": 892.5,
        },
        {
            "council_id": council_map["Manchester City Council"].id,
            "source": "idox_scraper",
            "status": "completed",
            "started_at": now - timedelta(hours=3),
            "completed_at": now - timedelta(hours=2, minutes=30),
            "records_found": 28,
            "records_created": 3,
            "records_updated": 8,
            "records_skipped": 17,
            "errors_count": 0,
            "duration_seconds": 1805.2,
        },
        {
            "council_id": council_map["Birmingham City Council"].id,
            "source": "idox_scraper",
            "status": "completed",
            "started_at": now - timedelta(hours=4),
            "completed_at": now - timedelta(hours=3, minutes=40),
            "records_found": 22,
            "records_created": 2,
            "records_updated": 6,
            "records_skipped": 14,
            "errors_count": 0,
            "duration_seconds": 1200.8,
        },
        {
            "source": "planning_data_api",
            "status": "completed",
            "started_at": now - timedelta(hours=6),
            "completed_at": now - timedelta(hours=5, minutes=20),
            "records_found": 156,
            "records_created": 22,
            "records_updated": 45,
            "records_skipped": 89,
            "errors_count": 0,
            "duration_seconds": 2400.0,
        },
        {
            "source": "find_a_tender",
            "status": "completed",
            "started_at": now - timedelta(hours=8),
            "completed_at": now - timedelta(hours=7, minutes=50),
            "records_found": 12,
            "records_created": 4,
            "records_updated": 3,
            "records_skipped": 5,
            "errors_count": 0,
            "duration_seconds": 600.0,
        },
        {
            "council_id": council_map["Leeds City Council"].id,
            "source": "idox_scraper",
            "status": "failed",
            "started_at": now - timedelta(hours=5),
            "completed_at": now - timedelta(hours=4, minutes=55),
            "records_found": 0,
            "records_created": 0,
            "records_updated": 0,
            "records_skipped": 0,
            "errors_count": 1,
            "error_details": {
                "errors": [
                    {
                        "type": "ConnectionError",
                        "message": "Failed to connect to planning portal: Connection timed out after 30s",
                        "timestamp": (now - timedelta(hours=4, minutes=55)).isoformat(),
                    }
                ]
            },
            "duration_seconds": 300.0,
        },
        {
            "source": "epc",
            "status": "completed",
            "started_at": now - timedelta(hours=12),
            "completed_at": now - timedelta(hours=11),
            "records_found": 85,
            "records_created": 15,
            "records_updated": 30,
            "records_skipped": 40,
            "errors_count": 0,
            "duration_seconds": 3600.0,
        },
        {
            "council_id": council_map["London Borough of Southwark"].id,
            "source": "idox_scraper",
            "status": "running",
            "started_at": now - timedelta(minutes=10),
            "records_found": 8,
            "records_created": 1,
            "records_updated": 3,
            "records_skipped": 4,
            "errors_count": 0,
        },
    ]

    runs = []
    for data in runs_data:
        run = ScraperRun(**data)
        session.add(run)
        runs.append(run)

    session.flush()
    print(f"  Seeded {len(runs)} scraper runs.")
    return runs


def main():
    """Main entry point."""
    print("=" * 60)
    print("UK Operations BD Platform - Database Initialization")
    print("=" * 60)
    print(f"\nDatabase URL: {DATABASE_URL}")
    print()

    engine = create_engine(DATABASE_URL, echo=False)
    create_tables(engine)

    with Session(engine) as session:
        try:
            councils = seed_councils(session)
            companies = seed_companies(session)
            applications = seed_planning_applications(session, councils, companies)
            schemes = seed_schemes(session, councils, companies)
            seed_pipeline_opportunities(session, applications, companies, councils)
            seed_alerts(session, applications, companies, councils, schemes)
            seed_scraper_runs(session, councils)

            session.commit()
            print("\n" + "=" * 60)
            print("Database initialization complete!")
            print("=" * 60)

        except Exception as e:
            session.rollback()
            print(f"\nERROR: Database seeding failed: {e}")
            raise


if __name__ == "__main__":
    main()
